apiVersion: v1
kind: Service
metadata:
  name: emergency-surge-backend
  namespace: aks-mrgnc-surge-dev
spec:
  selector:
    app: emergency-surge-backend
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: LoadBalancer