trigger:
- develop

pool:
  name: mrgnc-self-hosted

steps:
- script: |
    kubectl config current-context
    kubectl get ns
    kubectl apply -f k8s/dev/backend-deployment.yaml
    kubectl apply -f k8s/dev/backend-service.yaml
    kubectl rollout status deployment/emergency-surge-backend -n aks-mrgnc-surge-dev
    kubectl get all -n aks-mrgnc-surge-dev
  displayName: 'Deploy backend to Dev'